### ISSUE TITLE
Growth Charts

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/cgm-scanner#10]
- [x] use MPAndroidChart "Time Chart" but with multiple lines like the "Multiple Lines Chart" Example
- [x] start with Age/Height --> Length/height-for-age

include the following files as a static asset into the app:
for girls: http://www.who.int/childgrowth/standards/lhfa_girls_p_exp.txt
for boys: http://www.who.int/childgrowth/standards/lhfa_boys_p_exp.txt

- [x] draw lines from day 0 to current age in days + 100 for the data in the following columns
  - P3
  - P15
  - P50
  - P85
  - P97

It should look something like this for a child that is 5 years old. For younger children the chart is cut off.
http://www.who.int/childgrowth/standards/cht_lhfa_girls_p_0_5.pdf

- [x] also draw a thick black line for the measurements of the child

do the same with

- [ ] "Age / Weight" --> "Weight-for-age"
- [ ] [Weight-for-age (girls)](http://www.who.int/childgrowth/standards/wfa_girls_p_exp.txt)
- [ ] [Weight-for-age (boys)](http://www.who.int/childgrowth/standards/wfa_boys_p_exp.txt)

- [ ] "Height / Weight --> "Weight-for-height"
- [ ] [Weight-for-height (girls)](http://www.who.int/childgrowth/standards/wfh_girls_p_exp.txt)
- [ ] [Weight-for-height (boys)](http://www.who.int/childgrowth/standards/wfh_boys_p_exp.txt)

- [ ] new chart "Weight-for-length"
- [ ] [Weight-for-length (girls)](http://www.who.int/childgrowth/standards/wfl_girls_p_exp.txt)
- [ ] [Weight-for-length (boys)](http://www.who.int/childgrowth/standards/wfl_boys_p_exp.txt)

- [ ] new chart "Head circumference-for-age"
- [ ] [Head circumference-for-age (girls)](http://www.who.int/childgrowth/standards/second_set/hcfa_girls_p_exp.txt)
- [ ] [Head circumference-for-age (boys)](http://www.who.int/childgrowth/standards/second_set/hcfa_boys_p_exp.txt)

- [ ] new chart "Arm circumference-for-age"
- [ ] [Arm circumference-for-age (girls)](http://www.who.int/childgrowth/standards/second_set/acfa_girls_p_exp.txt)
- [ ] [Arm circumference-for-age (boys)](http://www.who.int/childgrowth/standards/second_set/acfa_boys_p_exp.txt)

**Comment by mmatiaschek** [comment]
partly implemented in v1.3.2
continued in #67
