### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/cgm-scanner#30]
- [ ] All Strings that are shown to the user must be in strings.xml
- [ ] As a user i want to be able to choose my main language (default from system language)
- [ ] the app should be able to display hindi हिन्दी letters
