### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/cgm-scanner#41]
- [x] trace performance of scanning process (frames per second)
- [x] trace upload performance
- [x] trace writeToFile performance

**Comment by mmatiaschek** [comment]
completed in 1.3.1
