### ISSUE TITLE
service for syncing local storage with Firebase Storage

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/cgm-scanner#6]
# The service will be used to store and sync:
- picture of the consent of parents with QR code
- scan artefacts
  - mp4 video files from RecorderActivity
  - .vtk or .pcd files with point clouds from RecorderActivity

# TODOs:
- [ ] use local storage for getting consent pictures
- [ ] if consent picture is not available from local storage get it from Firebase Storage
- [ ] make it optional to delete files from local storage after sync

**Comment by mmatiaschek** [comment]
first implementation for upload could be as easy as in RecorderActivity

```
// Direct Upload to Firebase Storage
            uploadFromUri(Uri.fromFile(file));
```
```
    private void uploadFromUri(Uri fileUri) {
        Log.d(TAG, "uploadFromUri:src:" + fileUri.toString());

        // Start MyUploadService to upload the file, so that the file is uploaded
        // even if this Activity is killed or put in the background
        startService(new Intent(this, FirebaseUploadService.class)
                .putExtra(FirebaseUploadService.EXTRA_FILE_URI, fileUri)
                .putExtra(AppConstants.EXTRA_QR, mQrCode)
                .putExtra(AppConstants.EXTRA_SCANTIMESTAMP, mNowTimeString)
                .setAction(FirebaseUploadService.ACTION_UPLOAD));
    }
```

**Comment by mmatiaschek** [comment]
the location for the upload has to be specified for the type of file

- Consent pictures saved with the person
- point clouds and images saved with the scan/measurement in different folders
